# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-19 03:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_auto_20160518_2346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dobrange',
            name='person',
        ),
        migrations.AddField(
            model_name='dobrange',
            name='dob',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='people.Dob'),
            preserve_default=False,
        ),
    ]
