# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-20 01:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_auto_20160518_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='street_prefix',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
