# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-20 01:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0007_auto_20160519_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='building',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
