# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-20 22:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0009_auto_20160519_2134'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactImport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(blank=True, max_length=256, null=True)),
                ('salutation', models.CharField(blank=True, max_length=32, null=True)),
                ('firstName', models.CharField(blank=True, max_length=32, null=True)),
                ('middleName', models.CharField(blank=True, max_length=32, null=True)),
                ('lastName', models.CharField(blank=True, max_length=32, null=True)),
                ('nameSuffix', models.CharField(blank=True, max_length=32, null=True)),
                ('nickName', models.CharField(blank=True, max_length=32, null=True)),
                ('fullTextAddress', models.CharField(blank=True, max_length=256, null=True)),
                ('streetPrefix', models.CharField(blank=True, max_length=32, null=True)),
                ('houseNumber', models.CharField(blank=True, max_length=32, null=True)),
                ('streetName', models.CharField(blank=True, max_length=32, null=True)),
                ('streetSuffix', models.CharField(blank=True, max_length=32, null=True)),
                ('apartment', models.IntegerField(blank=True, null=True)),
                ('building', models.IntegerField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=32, null=True)),
                ('state', models.CharField(blank=True, max_length=32, null=True)),
                ('zip', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
