# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-21 21:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0011_csvupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvupload',
            name='title',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
    ]
