# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-27 01:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0013_auto_20160525_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='person',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='people.Person'),
            preserve_default=False,
        ),
    ]
