# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-27 01:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0014_contact_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='zip',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
