# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-27 02:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0015_auto_20160526_2151'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person',
            new_name='PersonData',
        ),
    ]
