# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-27 02:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0016_auto_20160526_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='persondata',
            name='pipl_id',
            field=models.CharField(default=123456789, max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='persondata',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
