# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-27 02:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0017_auto_20160526_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persondata',
            name='pipl_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
