# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-07 00:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0019_auto_20160527_2103'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Name',
            new_name='NameData',
        ),
    ]
