# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-10 01:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0021_auto_20160608_2025'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Address',
            new_name='AddressData',
        ),
        migrations.RenameModel(
            old_name='Contact',
            new_name='ContactData',
        ),
        migrations.RenameModel(
            old_name='Dob',
            new_name='DobData',
        ),
        migrations.RenameModel(
            old_name='Email',
            new_name='EmailData',
        ),
        migrations.RenameModel(
            old_name='Ethnicity',
            new_name='EthnicityData',
        ),
        migrations.RenameModel(
            old_name='Gender',
            new_name='GenderData',
        ),
        migrations.RenameModel(
            old_name='Language',
            new_name='LanguageData',
        ),
        migrations.RenameModel(
            old_name='Phone',
            new_name='PhoneData',
        ),
        migrations.RenameModel(
            old_name='Relationship',
            new_name='RelationshipData',
        ),
        migrations.RenameModel(
            old_name='Url',
            new_name='UrlData',
        ),
        migrations.RenameModel(
            old_name='UserId',
            new_name='UserIdData',
        ),
    ]
