# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-10 02:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0023_auto_20160609_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='urldata',
            name='sourceId',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
