# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-11 19:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0024_urldata_sourceid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactdata',
            name='person',
        ),
        migrations.AddField(
            model_name='persondata',
            name='contact',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='people.ContactData'),
            preserve_default=False,
        ),
    ]
