# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-11 22:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0026_auto_20160611_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressdata',
            name='display',
            field=models.CharField(default=19, max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='addressdata',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='people.PersonData'),
        ),
        migrations.AlterField(
            model_name='dobdata',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dobs', to='people.PersonData'),
        ),
        migrations.AlterField(
            model_name='emaildata',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='people.PersonData'),
        ),
        migrations.AlterField(
            model_name='ethnicitydata',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ethnicities', to='people.PersonData'),
        ),
        migrations.AlterField(
            model_name='genderdata',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gender', to='people.PersonData'),
        ),
        migrations.AlterField(
            model_name='languagedata',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='people.PersonData'),
        ),
        migrations.AlterField(
            model_name='namedata',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='names', to='people.PersonData'),
        ),
        migrations.AlterField(
            model_name='phonedata',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone', to='people.PersonData'),
        ),
        migrations.AlterField(
            model_name='relationshipdata',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships', to='people.PersonData'),
        ),
        migrations.AlterField(
            model_name='urldata',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urls', to='people.PersonData'),
        ),
        migrations.AlterField(
            model_name='useriddata',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userids', to='people.PersonData'),
        ),
    ]
