# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-11 22:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0027_auto_20160611_1841'),
    ]

    operations = [
        migrations.RenameField(
            model_name='urldata',
            old_name='sourceId',
            new_name='source_id',
        ),
    ]
