# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-12 22:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0029_auto_20160612_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactdata',
            name='company',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='contactdata',
            name='title',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
