# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-03 15:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0031_auto_20160612_1904'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addressdata',
            options={'permissions': (('view_addressdata', 'Can view address data'),)},
        ),
        migrations.AlterModelOptions(
            name='contactdata',
            options={'permissions': (('view_contactdata', 'Can view contact data'),)},
        ),
        migrations.AlterModelOptions(
            name='csvupload',
            options={'permissions': (('view_csvupload', 'Can view CSV uploads'),)},
        ),
        migrations.AlterModelOptions(
            name='dobdata',
            options={'permissions': (('view_dobdata', 'Can view dob data'),)},
        ),
        migrations.AlterModelOptions(
            name='emaildata',
            options={'permissions': (('view_emaildata', 'Can view email data'),)},
        ),
        migrations.AlterModelOptions(
            name='ethnicitydata',
            options={'permissions': (('view_ethnicitydata', 'Can view ethnicity data'),)},
        ),
        migrations.AlterModelOptions(
            name='genderdata',
            options={'permissions': (('view_genderdata', 'Can view gender data'),)},
        ),
        migrations.AlterModelOptions(
            name='languagedata',
            options={'permissions': (('view_languagedata', 'Can view language data'),)},
        ),
        migrations.AlterModelOptions(
            name='namedata',
            options={'permissions': (('view_namedata', 'Can view name data'),)},
        ),
        migrations.AlterModelOptions(
            name='persondata',
            options={'permissions': (('view_persondata', 'Can view person data'),)},
        ),
        migrations.AlterModelOptions(
            name='phonedata',
            options={'permissions': (('view_phonedata', 'Can view phone data'),)},
        ),
        migrations.AlterModelOptions(
            name='relationshipdata',
            options={'permissions': (('view_relationshipdata', 'Can view relationship data'),)},
        ),
        migrations.AlterModelOptions(
            name='urldata',
            options={'permissions': (('view_urldata', 'Can view URL data'),)},
        ),
        migrations.AlterModelOptions(
            name='useriddata',
            options={'permissions': (('view_useriddata', 'Can view user ID data'),)},
        ),
    ]
