# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-04 00:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        ('people', '0033_contactdata_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactdata',
            name='owner',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
            preserve_default=False,
        ),
    ]
