# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-09 16:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0036_auto_20160704_1514'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagesData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_since', models.DateField(blank=True, null=True)),
                ('url', models.URLField()),
                ('thumbnain_token', models.CharField(blank=True, max_length=256, null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='people.PersonData')),
            ],
        ),
    ]
