# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-09 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0037_imagesdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='persondata',
            name='matched',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
